name: Renovate

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0/15 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.app_id  }}
          private-key: ${{ secrets.app_private_key }}
          owner: ${{ github.repository_owner }}

      - uses: renovatebot/github-action@v41.0.2
        with:
          configurationFile: renovate-config.js
          token: "${{ steps.app-token.outputs.token }}"
        env:
          LOG_LEVEL: "debug"
